# Generated by Django 3.2.4 on 2021-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LITReview', '0005_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
